name: react-native-codepush-release
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-ios:
    runs-on: ubuntu-latest

    steps: 
      - name: Install AppCenter CLI
        run: npm install -g appcenter-cli

      - uses: actions/checkout@v3

      - name: Authenticate to Github packages
        run: |
          echo "@youfoundation:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_PAT }}" >> .npmrc    

      - name: Install npm dependencies
        run: npm ci

      - name: Build Android package
        run: npm run build:android-codepush -w packages/mobile
        
      - name: Deploy to CodePush Android
        run: npm run release:codepush -w packages/mobile
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN_ANDROID }}

      # - name: Build iOS package
      #   run: npm run build:ios-codepush -w packages/mobile
        
      # - name: Deploy to CodePush iOS
      #   run: npm run release:codepush -w packages/mobile
      #   env:
      #     APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN_IOS }}