name: 'CI to netlify'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy to Netlify'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_SITE_ID: 5e581e51-e8be-4871-8e5f-156eef719f6c
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: npm install
          build_command: npm run build
          build_directory: dist
